### ISSUE TITLE
Sizes are displayed as "ko"

### ISSUE THREAD

**Issue by aej11a** [josselinbuils/next-bundle-analyzer#2]
Is this a typo? I would guess that this should say "kb" or "KB" (to match the original bundle analyzer). I'd be happy to submit a PR to fix it!

<img width="527" alt="image" src="https://user-images.githubusercontent.com/10066422/209260711-addb0d16-c993-42bf-816c-b82647ff1ecc.png">

**Comment by josselinbuils** [comment]
Hello, I initially made it for my own purposes so I used this familiar unit but no problem to change it.

The right case to use is **kB**, feel free to make a MR, otherwise I'm going to change it when I have time 🙂
